rockchip-burn: update edge-2l
Signed-off-by: hyphop <art@khadas.com>

diff --git a/rockchip-burn b/rockchip-burn
--- a/rockchip-burn
+++ b/rockchip-burn
@@ -7,7 +7,9 @@
 
 
 HELP(){ cat <<HELP_
-USAGE rockchip-burn [IMAGE_NAME] [ARGS...]
+USAGE
+
+[ENV] rockchip-burn [edge2l] [IMAGE_NAME] [ARGS...]
 
 ## VER 0.144
 
@@ -20,10 +22,17 @@ ARGS
     --help
     --update
     --list
+    --test
+    --edge2l
 
-IMAGE_NAME
+IMAGE_NAME TAGS
 
     oowow | android | ubuntu
+
+ENV VAR=value
+
+    MIRROR [dl.khadas.com|dl.khadas.cn]
+    ...
 
 EXAMPLES
 
@@ -59,22 +68,35 @@ HELP_
 exit
 }
 
-for VER in $(grep -m1 VER "$0"); do true; done
+usb_find(){
+	local VID=${1-2207}
+	local d
+	local p
+	for d in /sys/bus/usb/devices/*; do
+		[ -f "$d/idVendor" ] || continue
+		read v < "$d/idVendor"
+		[ "$v" = "$VID" ] || continue
+		read p < "$d/idProduct"
+		#echo "+ $d $p">&2
+		case $p in
+			330c|350b|350e)
+			echo "$v:$p"
+			;;
+		esac
+	done
+}
 
+NAME=rockchip-burn
 PROG=$(realpath -s "$0")
 WORK=$(dirname "$PROG")
 
-NAME=rockchip-burn
-SOURCE=https://raw.githubusercontent.com/hyphop/rockchip-burn/main/$NAME
-
-LOADER=${LOADER-rk3588_spl_loader_v1.07.111.bin}
-TOOL=${TOOL-upgrade_tool}
-
-TOOL_DL=${TOOL_DL-https://raw.githubusercontent.com/khadas/utils/master/rk-flash-tool/tools/Linux_Upgrade_Tool/$TOOL}
-LOADER_DL=${LOADER_DL-http://dl.khadas.com/products/edge2/firmware/boot/$LOADER}
-
 TOOL_HOME=~/upgrade_tool
-TOOL_BIN=$TOOL_HOME/bin
+TOOL_BIN="$TOOL_HOME/bin"
+
+: ${MIRROR:=dl.khadas.com}
+echo "MIRROR: $MIRROR"
+: ${SOURCE:=https://raw.githubusercontent.com/hyphop/rockchip-burn/main/$NAME}
+: ${DL_OOWOW:=$MIRROR/products/oowow/system/}
 
 FAIL(){
     echo "[e] $@">&2
@@ -86,6 +108,10 @@ MSG(){
 CMD(){
     echo "### $@">&2
     "$@"
+}
+CMDF(){
+    echo "### $@">&2
+    "$@" || exit 1
 }
 
 lowcase(){
@@ -134,21 +160,56 @@ CHK(){
     }
 }
 
-echo "rockchip-burn $@">&2
+usb_list(){
+echo "Usb list:"
+usb_find
+#echo $USB_ID
+}
 
+debug(){
+[ "$DEBUG" ] || return
+echo "$@">&2
+}
 
-DST=${DST-emmc}
+debug "rockchip-burn $@">&2
+for VER in $(grep -m1 VER "$0"); do true; done
+
+: ${DST:=emmc}
 TYPE=sd
-
 RESET=1
 
-BOARD=${BOARD-edge2}
+case $1 in
+	edge2l) BOARD=edge-2l ; shift ;;
+esac
+
+USB_ID=$(usb_find)
+debug "usb_id: +$USB_ID+"
+
+case $USB_ID in
+	2207:350e) BOARD=edge-2l ;;
+esac
+
+: ${BOARD:=edge2}
 board=$(lowcase $BOARD)
 
-DL_OOWOW=http://dl.khadas.com/products/oowow/system/
+case $board in
+	edge-2l) LOADER=rk3576_spl_loader_v1.10.108.bin ;;
+esac
+
+: ${LOADER:=rk3588_spl_loader_v1.08.111.bin}
+: ${TOOL:=upgrade_tool}
+: ${TOOL_DL:=https://raw.githubusercontent.com/khadas/utils/master/rk-flash-tool/tools/Linux_Upgrade_Tool/$TOOL}
+: ${LOADER_DL:=$MIRROR/products/$board/firmware/boot/$LOADER}
+: ${UT:=$TOOL_BIN/$TOOL}
 
 for a in "$@"; do
     case $a in
+	-t|--test)
+	echo "Test mode"
+	usb_list
+	CMD $UT -v
+	exit
+	;;
 	-v|--version)
 	echo $VER && exit
 	;;
@@ -168,6 +229,7 @@ for a in "$@"; do
 	--spi)
 	DST=spi
 	TYPE=spi
+	DEST=SPINOR
 	;;
 	-w|--write)
 	MODE=write
@@ -213,10 +275,13 @@ for a in "$@"; do
     esac
 done
 
+DL=${DL:-$MIRROR/.images/$board/}
+
 case $MODE in
     ""|help)
     HELP
     ;;
+
     update)
 
     RND=${RANDOM-$$}
@@ -266,14 +331,18 @@ CHK "$LOADER" "$LOADER_DL" || FAIL "loader"
 
 UDEV=/etc/udev/rules.d/80-rockchip-usb.rules
 
-grep -q OKAY $UDEV 2>/dev/null || {
+grep -q OKAY2 $UDEV 2>/dev/null || {
 
 MSG "install usb device permission to $UDEV, need admin permissions!"
 
 cat <<EOF | sudo tee $UDEV
-#OKAY
+#OKAY2
+#Maskrom
 SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="2207", ATTR{idProduct}=="330c", MODE:="0666"
+#Loader
 SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="2207", ATTR{idProduct}=="350b", MODE:="0666"
+#Rockchip Maskrom (new generation)
+SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="2207", ATTR{idProduct}=="350e", MODE:="0666"
 EOF
 
 }
@@ -283,42 +352,110 @@ EOF
 export PATH="$TOOL_BIN:$PATH"
 #echo $PATH
 
-which $TOOL || FAIL "cant find $TOOL"
+loader(){
+	local DEST
+	CMDF $TOOL LD | grep Mode=Maskrom
+	CMDF $TOOL DB "bin/$LOADER" $DEST
+	sleep 1
+	CMDF $TOOL RCI
+	CMDF $TOOL RCB
+	#CMDF $TOOL UL "bin/$LOADER" -noreset $DEST
+	sleep 1
+}
 
+setup_dst(){
+case $DST in
+    spi)
+    CMD $TOOL SSD 5
+    ;;
+    *)
+    #CMD $TOOL SSD
+    CMD $TOOL SSD 2 # EMMC
+    ;;
+esac
+sleep 1
+}
+
+which $TOOL || FAIL "cant find $TOOL"
 
 case $MODE in
     clean)
-    FAIL "not ready"
-    ;;
+	echo "Clean storage $DST"
+	loader    || FAIL "oops loader fail"
+	setup_dst || FAIL "oops can setup DST: $DST"
+
+	case $DST in
+		SPI|spi)
+	CMDF $TOOL EL 0x4000 0x10
+	CMDF $TOOL EL 0x5000 0x10
+		;;
+		*)
+	CMDF $TOOL EL 0x0 0x100000
+		;;
+	esac
+	exit
+	;;
 esac
 
-DL=${DL:-http://dl.khadas.com/.images/$BOARD/}
 
 case $SRC in
     oowow)
     DL=$DL_OOWOW
+    DST=spi
+    TYPE=spi
     FILE=$BOARD-oowow-latest-$TYPE.img.gz
+    #DST=spi
     ;;
-    android)
-    FILE=$BOARD-android-12-v230114.raw.img.xz
-    DST=emmc
-    ;;
-    ubuntu)
-    FILE=$BOARD-ubuntu-22.04-gnome-linux-5.10-fenix-1.4-221229.img.xz
-    DST=emmc
-    ;;
+#    android)
+ #   FILE=$BOARD-android-12-v230114.raw.img.xz
+  #  DST=emmc
+  #  ;;
+ #   ubuntu)
+  #  FILE=$BOARD-ubuntu-22.04-gnome-linux-5.10-fenix-1.4-221229.img.xz
+   # DST=emmc
+   # ;;
 esac
 
-case $MODE-$SRC in
+get_list(){
+
+case $1-$2 in
+    list-)
+    echo "!$1">&2
+    LL="dl/$board.list"
+    GET - "$DL" | grep -o "${board}-[^\" ]*\.xz" | sort -u | tee "$LL"
+    echo "$DL" > "$LL.url"
+    ;;
     list-oowow)
-    echo "$MODE-$SRC:">&2
-    GET - ${DL}versions/$board 2>/dev/null | grep -o $board-$SRC-..........-$TYPE.img.gz | uniq | sort
-    exit 0
+    echo "!$1-$2:">&2
+    DD= "${DL}versions/$board"
+    LL="dl/$board-oowow.list"
+    GET - "$DD" 2>/dev/null | grep -o $board-$SRC-..........-$TYPE.img.gz | sort -u | tee "$DD"
+    echo "$DD" > "$LL.url"
+    ;;
+    *)
+    #echo "??? $MODE-$SRC"
     ;;
 esac
+}
+
+get_list $MODE $SRC
+
+[ "$MODE" = "list" ] && exit
+
+[ "$1" ] && {
+echo --
+D=dl/$board.list
+[ -s "$D" ] || get_list list
+F=$(grep -m1 "$1" "$D")
+[ "$F" ] && FILE="$F" && DL=$(cat "$D.url")
+echo "[$@]"
+echo --
+}
 
 PKG=dl/$FILE
 IMG=${PKG%.*}
+
+echo MODE $MODE
 
 [ "$REFRESH" ] && {
     MSG "refresh mode"
@@ -344,13 +481,13 @@ case $PKG in
     *.gz)
     [ "$gz" ] || INSTALL gzip pigz
     MSG "decompress $PKG wait..."
-    CMD $gz -dc $PKG > $IMG || FAIL "decompress fail"
+    CMD $gz -dc < $PKG > $IMG || FAIL "decompress fail"
     LOCAL=
     ;;
     *.xz)
     [ "$xz" ] || INSTALL pixz xz
     MSG "decompress $PKG wait..."
-    CMD $xz -dc $PKG > $IMG || FAIL "decompress fail"
+    CMD $xz -dc < $PKG > $IMG || FAIL "decompress fail"
     LOCAL=
     ;;
 esac
@@ -378,29 +515,23 @@ done
 echo
 
 echo "[i] check is ready ..."
-$TOOL TD || $TOOL DB bin/$LOADER || exit 4
 
-case $DST in
-    spi)
-    echo $IMG
-(
-sleep 1
-echo 1
-echo RCB
-sleep 2
-echo SSD
-echo 5
-echo WL 0 $IMG
-echo Q
-) | $TOOL || FAIL "oops"
-    ;;
-    emmc)
-    CMD $TOOL WL 0 "$IMG" || FAIL "oops"
-    ;;
-esac
+#$TOOL TD || $TOOL DB "bin/$LOADER" || exit 4
+loader
+setup_dst
 
-[ "$FILE" ] && \
-echo "\n[i] OKAY $FILE was written to $DST"
+CMD $TOOL WL 0 "$IMG" || FAIL "oops"
 
+[ "$FILE" ]  && echo && echo "[i] OKAY $FILE was written to $DST"
 [ "$RESET" ] && MSG "reset device" && CMD $TOOL RD 0
 [ "$RESET" ] || MSG "no reset device"
+
+exit
+<<EOF
+
+# edge2l
+Bus 007 Device 033: ID 2207:350e Fuzhou Rockchip Electronics Company
+
+# edge2
+Bus 007 Device 035: ID 2207:350b Fuzhou Rockchip Electronics Company
+
